const data = {
    products: [
        {
            _id: '1',
            name: 'Nike Slim Shirts',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Product',
        },
        {
            _id: '2',
            name: 'Adidas Fit Shirt',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price: 100,
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 10,
            description: 'High Quality Product',
        },
        {
            _id: '3',
            name: 'Peter England Shirts',
            category: 'Shirts',
            image: '/images/p3.jpg',
            price: 220,
            brand: 'Peter England',
            rating: 4.9,
            numReviews: 15,
            description: 'High Quality Product',
        },
        {
            _id: '4',
            name: 'Nike Slim Pants',
            category: 'Pants',
            image: '/images/p4.jpg',
            price: 90,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 14,
            description: 'High Quality Product',
        },
        {
            _id: '5',
            name: 'Puma Slim Pants',
            category: 'Pants',
            image: '/images/p5.jpg',
            price: 95,
            brand: 'Puma',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Product',
        },
        {
            _id: '6',
            name: 'Adidas Fit Pants',
            category: 'Pants',
            image: '/images/p6.jpg',
            price: 105,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 8,
            description: 'High Quality Product',
        },
    ],
};

export default data;